server:
  port: 9001
spring:  application:    name: movie-catalog-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviecatalogservice?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
eureka:  instance:    lease-renewal-interval-in-seconds: 30
  client:    service-url:
      defaultZone: http://localhost:8761/eureka/