server:
  port: 9002
spring:
  application:
    name: movie-details-service  datasource:    driver-class-name: com.mysql.jdbc.driver
    url: jdbc.mysql://localhost:3306/moviedetailsservice
    username: root
    password: root
  jpa:    hibernate:      ddl-auto: update
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/